name: she_aware
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  avatar_glow: ^3.0.1
  flutter_card_swiper: ^7.1.0
  flutter_layout_grid: ^2.0.8
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  device_preview: ^1.2.0
  dio: ^5.7.0
  carousel_slider_plus: ^7.1.1
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  flutter_launcher_icons: ^0.13.1
  #  flutter_local_notifications: ^19.1.0
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  toastification: ^3.0.3
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  http_parser: ^4.0.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  just_audio: ^0.9.36
  jwt_decoder: ^2.0.1
  logger: ^2.5.0
  logging: ^1.2.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  permission_handler: ^11.3.1
  record: ^6.0.0
  dartz: ^0.10.1
  share_plus: ^10.1.4
  shared_preferences: ^2.3.5
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  simple_ripple_animation: ^0.1.0
  flutter_animate: ^4.0.0
  lottie: ^3.3.1
  stepper_list_view: ^0.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_tts: ^4.2.3
  circular_countdown_timer: ^0.2.4
  confetti: ^0.8.0
  animated_leaderboard: ^0.1.4
  icons_launcher: ^3.0.3
  lottie_screen_onboarding_flutter: ^1.1.3
  flutter_html: ^3.0.0
  flutter_markdown: ^0.7.4+1
  fl_chart: ^0.69.0
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/fonts/
    - assets/animations/
